### ISSUE TITLE
Use semantic-release for automatic publishing

### ISSUE THREAD

**Issue by satya164** [callstack-io/eslint-config-callstack-io#9]

**Comment by thymikee** [comment]
Do you have any experience in this matter?

**Comment by satya164** [comment]
@thymikee yea, you just need to run the cli to set it up. then it'll automatically publish to npm when the ci passes. we need to follow a convention for commit messages and prefix them with `feat`, `fix`, `chore` etc. so it can determine the new version according to semver rules and generate a proper changelog.

**Comment by thymikee** [comment]
I'll give it a try 👍

**Comment by thymikee** [comment]
@satya164 is this expected?

<img width="731" alt="screen shot 2017-08-01 at 15 44 52" src="https://user-images.githubusercontent.com/5106466/28828250-6a1dae8a-76d0-11e7-8325-a3fb55a030be.png">

**Comment by satya164** [comment]
@thymikee I believe so. it won't publish unless there are `feat`, `fix` or `BREAKING` I think

**Comment by thymikee** [comment]
Ok, closing then
